### ISSUE TITLE
Some infinite looping bug occurred

### ISSUE THREAD

**Issue by CodeBiang** [grepthat/libOpenDRIVE#12] opened 2021-12-02 01:39 UTC
```cpp
// at Lanes.cpp#187
            for (const auto& s_roadmarks_line : roadmark_group.s_to_roadmarks_line)
            {
                const RoadMarksLine& roadmarks_line = s_roadmarks_line.second;
                if (roadmarks_line.width > 0)
                    width = roadmarks_line.width;
                // roadmarks_line.length + roadmarks_line.space equals zero in some xodr files
                for (double s_start_single_roadmark = s_roadmarks_line.first; s_start_single_roadmark < s_end_roadmark_group;
                     s_start_single_roadmark += (roadmarks_line.length + roadmarks_line.space))
                {
                    const double s_end_single_roadmark = std::min(s_end, s_start_single_roadmark + roadmarks_line.length);
                    roadmarks.push_back(
                        {s_start_single_roadmark, s_end_single_roadmark, roadmarks_line.t_offset, width, roadmark_group.type + roadmarks_line.name});
                }
            }
```
roadmarks_line.length + roadmarks_line.space equals zero in some xodr files

in addition, I want to further encapsulate this library with typescript. Any suggestions？

**Comment by grepthat** [comment] 2021-12-08 17:19
duplicate of #13

**Closed by grepthat** 2021-12-08 17:19 UTC
