### ISSUE TITLE
compilation error on ubuntu 18.04, std::isnan<double> unknown

### ISSUE THREAD

**Issue by cpsoymilk** [grepthat/libOpenDRIVE#46] opened 2022-10-05 07:49 UTC
![Cache_-4606284376c952b5](https://user-images.githubusercontent.com/107377601/194008082-2e8a65c4-95a3-4f46-a437-d24761c9737b.jpg)
I guess the version of my "cmake" is inconsistent with yours. Can you tell me your version of cmake

**Comment by cpsoymilk** [comment] 2022-10-05 07:51
The version of mine is 3.10.2

**Comment by cpsoymilk** [comment] 2022-10-05 07:57
The version of my ubuntu is 18.04

**Comment by dongtaihong** [comment] 2022-10-08 03:13
> 

you need to replace all std::nan<double>() with std::nan()

**Comment by dongtaihong** [comment] 2022-10-08 03:15
you need to replace all std::nan<<double>>() with std::nan

**Comment by dongtaihong** [comment] 2022-10-08 03:16
you need to replace all std::nan<>() with std::nan()

**Comment by cpsoymilk** [comment] 2022-10-08 03:20
ok，thanks a lot

**Comment by grepthat** [comment] 2022-10-08 07:47
You mean `NAN` with `std::nan()` ? There is no `std::nan` in the code?

**Comment by grepthat** [comment] 2022-10-08 07:48
@cpsoymilk which compiler version are you using? I can't reproduce.

**Comment by cpsoymilk** [comment] 2022-10-08 07:54
I changed the version from master to 0.2.0, and then it works normally
![image](https://user-images.githubusercontent.com/107377601/194696604-845dc676-bae8-46c3-ab8c-99822381d6e9.png)

**Comment by grepthat** [comment] 2022-10-08 07:56
@cpsoymilk Which compiler version and OS were you using? This is an error that should be fixed.

**Comment by cpsoymilk** [comment] 2022-10-08 08:22
Do you mean the version of "make"? Besides, I don't know what OS you mean. I'll show you tomorrow. It's in my office computer.

**Comment by grepthat** [comment] 2022-10-08 08:42
I mean which Operating System (OS), like Ubuntu 18.04, 20.04, Windows 10..? And wich compiler? (What do you get when you execute `c++ --version`) ?

**Comment by cpsoymilk** [comment] 2022-10-08 08:52
Okay, I'll get back to you later

**Comment by cpsoymilk** [comment] 2022-10-09 07:06
![sendpix5](https://user-images.githubusercontent.com/107377601/194742853-4d60bbcd-3b1f-4c43-adff-0b63639b3c50.jpg)
![sendpix6](https://user-images.githubusercontent.com/107377601/194742894-380c283f-04d7-4746-9bb3-93f01519dc9f.jpg)

**Comment by m0uH** [comment] 2022-11-14 12:01
Experiencing the same compilation errors when using CentOS 7 and GCC 8.3.1. Replacing `std::isnan<double>()` with `std::isnan()` fixes the problems.

**Comment by grepthat** [comment] 2023-02-20 20:19
should be fixed with https://github.com/grepthat/libOpenDRIVE/pull/52, feel free to reopen if it's still broken

**Closed by grepthat** 2023-02-20 20:19 UTC
Labels: bug
